services:
  mongito:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-nico}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      MONGO_URI: mongodb://${MONGO_USER:-nico}:${MONGO_PASSWORD:-password}@mongito:27017/${MONGO_DB:-gestion}?authSource=admin
      IVA_RATE: ${IVA_RATE:-0.15}
      TZ: America/Guayaquil
    depends_on:
      - mongito
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
